const data = [
  {
    name: "Evelyn",
    assignment: "SCRUM",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D1-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-5",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-4",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-5",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "5",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W1D4-1",
    difficulty: "4",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D1-1",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W2D1-2",
    difficulty: "2",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-3",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-3",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-4",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-3",
    difficulty: "3",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-2",
    difficulty: "4",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-3",
    difficulty: "3",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-4",
    difficulty: "4",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D4-1",
    difficulty: "5",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D4-2",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "2",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-1",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-2",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-3",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-4",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-1",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-3",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-4",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-5",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "1",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W5D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Evelyn",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W6D1-1",
    difficulty: "5",
    enjoyment: "5",
  },
  {
    name: "Evelyn",
    assignment: "W6D2-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Evelyn",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "5",
    enjoyment: "5",
  },
  {
    name: "Aranka",
    assignment: "SCRUM",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D1-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D2-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D2-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D2-3",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D2-4",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D2-5",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D3-4",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-5",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D4-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D1-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D1-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D3-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D3-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D3-3",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D4-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D4-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-1",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W3D1-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D3-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D4-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W3D4-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D2-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D2-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W4D2-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W4D2-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W4D3-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W4D3-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-5",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Aranka",
    assignment: "W5D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Aranka",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W6D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Aranka",
    assignment: "W6D2-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Aranka",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "SCRUM",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W1D1-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W1D2-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-5",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W1D3-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3-4",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W1D3-5",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W1D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W2D1-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W2D1-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W2D2-1",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W2D2-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W2D2-3",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W2D3-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W2D3-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W2D3-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W2D4-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W2D4-2",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W2D4-3",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W3D1-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-4",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W3D2-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W3D2-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W3D2-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W3D3-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W3D3-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W3D3-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W3D3-4",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W3D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W3D4-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W4D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W4D2-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W4D2-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W4D2-4",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W4D3-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Floris",
    assignment: "W4D3-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-4",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-5",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W5D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Floris",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W6D1-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Floris",
    assignment: "W6D2-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Floris",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "SCRUM",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W1D1-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W1D2-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W1D2-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W1D2-3",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W1D2-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W1D2-5",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W1D3-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W1D3-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W1D3-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W1D3-5",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W1D4-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W2D1-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W2D1-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D2-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W2D2-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D2-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D3-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W2D3-2",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D3-3",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D4-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W2D4-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W2D4-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W3D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W3D1-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W3D1-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W3D1-4",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W3D3-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W3D3-2",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W3D3-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W3D3-4",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W3D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W3D4-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W4D2-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W4D2-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W4D2-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W4D2-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W4D3-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W4D3-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-5",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W5D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Hector",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W6D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Hector",
    assignment: "W6D2-1",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Hector",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "SCRUM",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D1-1",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W1D2-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-4",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W1D2-5",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W1D3-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W1D3-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D3-4",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W1D3-5",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W1D4-1",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D1-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D1-2",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W2D2-1",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W2D2-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W2D2-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W2D3-1",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W2D3-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D3-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D4-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D4-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W3D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W3D1-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W3D1-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W3D1-4",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W3D2-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W3D2-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W3D2-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W3D3-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W3D3-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W3D3-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W3D3-4",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W3D4-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W3D4-2",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W4D2-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W4D2-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W4D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W4D2-4",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W4D3-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Martina",
    assignment: "W4D3-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W4D3-4",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W4D3-5",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Martina",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W5D4-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W6D1-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Martina",
    assignment: "W6D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Martina",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "SCRUM",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D1-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D2-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D2-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D2-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D2-5",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D3-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D3-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D3-4",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D3-5",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D1-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D2-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D2-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D2-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D3-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D3-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D3-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D4-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D4-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D1-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D1-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D1-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D1-4",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W3D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D2-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D2-3",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D3-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D3-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D3-3",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D3-4",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D4-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D4-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D2-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D2-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D2-3",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D2-4",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W4D3-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D3-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W4D3-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D3-4",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W4D3-5",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W5D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Maurits",
    assignment: "W6D1-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Maurits",
    assignment: "W6D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Maurits",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "SCRUM",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D1-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D2-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D2-3",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D2-4",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D2-5",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D3-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W1D3-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D3-4",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D3-5",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W1D4-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W2D1-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D1-2",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-3",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D3-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D3-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D3-3",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D4-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D4-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D4-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D1-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D1-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W3D1-4",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D2-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D2-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D2-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D3-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D3-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D3-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D3-4",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D4-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D4-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W4D2-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W4D2-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W4D2-3",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W4D2-4",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-4",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W4D3-5",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Rahima",
    assignment: "W5D4-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Rahima",
    assignment: "W6D1-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W6D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Rahima",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "SCRUM",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D1-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W1D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D2-5",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D3-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D3-4",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3-5",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D4-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D1-1",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W2D1-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D2-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W2D2-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D2-3",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D3-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D3-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D3-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D4-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W2D4-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D1-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-4",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D2-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D2-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D2-3",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-3",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D3-4",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D4-1",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D4-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W4D2-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D2-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W4D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D2-4",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D3-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-4",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-5",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W5D4-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Sandra",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Sandra",
    assignment: "W6D1-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Sandra",
    assignment: "W6D2-1",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Sandra",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "SCRUM",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D1-1",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W1D2-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D2-4",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D2-5",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3-1",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W1D3-2",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3-4",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D3-5",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D4-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D1-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D1-2",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D2-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W2D2-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D3-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D3-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D3-3",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D4-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D4-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D4-3",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D1-1",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D1-2",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D1-3",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D1-4",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D2-1",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D2-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D2-3",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D3-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D3-2",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W3D3-3",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D3-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D4-2",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D2-1",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D2-2",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D2-3",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W4D2-4",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D3-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W4D3-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W4D3-3",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D3-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D3-5",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W5D4-1",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Wietske",
    assignment: "W6D1-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W6D2-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Wietske",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "SCRUM",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W1D1-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W1D2-1",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-2",
    difficulty: "1",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-3",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W1D2-4",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-5",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W1D3-1",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W1D3-2",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W1D3-4",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W1D3-5",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W1D4-1",
    difficulty: "4",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W1D5 - Project -�Galgje",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W2D1-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W2D1-2",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W2D2-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W2D2-2",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W2D2-3",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W2D3-1",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W2D3-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W2D3-3",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W2D4-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W2D4-2",
    difficulty: "4",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W2D4-3",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W3D1-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W3D1-2",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W3D1-3",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W3D1-4",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W3D2-1",
    difficulty: "1",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W3D2-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W3D2-3",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W3D3-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W3D3-2",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W3D3-3",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W3D3-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W3D4-1",
    difficulty: "2",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W3D4-2",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: "3",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W4D2-1",
    difficulty: "2",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W4D2-2",
    difficulty: "3",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W4D2-3",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W4D2-4",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W4D3-1",
    difficulty: "3",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W4D3-2",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W4D3-3",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W4D3-4",
    difficulty: "3",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W4D3-5",
    difficulty: "2",
    enjoyment: "3",
  },
  {
    name: "Storm",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: "4",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W5D4-1",
    difficulty: "2",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: "1",
    enjoyment: "2",
  },
  {
    name: "Storm",
    assignment: "W6D1-1",
    difficulty: "4",
    enjoyment: "4",
  },
  {
    name: "Storm",
    assignment: "W6D2-1",
    difficulty: "1",
    enjoyment: "1",
  },
  {
    name: "Storm",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: "3",
    enjoyment: "3",
  },
];

export const names = data.map((item) => item.name);
export const tasks = data.map((item) => item.assignment);
// export const difficulty = data.map((item) => parseInt(item.difficulty));
// export const enjoyment = data.map((item) => parseInt(item.enjoyment));

export default data;
